version: '3'
services:
  db:
    image: postgres
    container_name: leaf_record_fb
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql
      - bundle_data:/usr/local/bundle
    ports:
      - 5432:5432
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./back:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    command: yarn dev -p 8000
    ports:
      - "8000:8000"
volumes:
  postgresql_data:
  bundle_data: